name: CI Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
        pip3 install pytest
    - name: Run unit tests
      run: |
        pytest -v tests/test_calculator.py
