name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Setup dependencies
    runs-on: ubuntu-latest
    outputs:
      python-version: '3.9'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install common dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage flake8
          
  unit_tests:
    needs: setup
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Reuse checkout and setup
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
          
      - name: Run unit tests
        run: |
          pytest -v
          coverage run -m pytest
          coverage report -m
          
  lint:
    needs: setup
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Reuse checkout and setup
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
          
      - name: Run lint
        run: flake8 calculator.py tests/
